---
title: "Open Access Monitor: Zeitschriftenlisten"
description: Der Open Access Monitor des Forschungszentrum Jülich dient für viele Bibliotheken als Datengrundlage zur Untersuchung des Transformationsprozesses von wissenschaftlichen deutschen Zeitschriften. Im April 2021 veröffentlichte das Forschungszentrum Jülich mehrere Zeitschriftenlisten, die den hybriden Zeitschriftenbestand des Open Access Monitors abdecken. Dieser Blogbeitrag demonstriert die Aggregation der verschiedenen Zeitschriftenlisten, sodass die Daten als einzelne vollständige Tabelle analysiert werden können.
author: 
  - Nick Haupka
date: July 16, 2021
preview: distill-preview.png
creative_commons: CC BY
output: distill::distill_article
---
  
```{r, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = TRUE
)
```

Seit 2018 erfasst der Open Access Monitor (OAM) Deutschland das Publikationsaufkommen deutscher akademischer Einrichtungen in wissenschaftlichen Zeitschriften. In diesem Zusammenhang werden Publikationsdaten und Publikationsstatistiken ermittelt, die im Rahmen strategischer Entscheidungsprozesse von Bibliotheken genutzt werden können. Ein besonderes Augenmerk obliegt hierbei dem Transformationsprozess von Closed Access zu Open Access. Dessen Entwicklung sowie die Analyse von bibliometrischen Kennzahlen im Publikationsaufkommen sind für Verhandlungen zwischen Bibliotheken und wissenschaftlichen Verlagen von entscheidender Bedeutung (etwa im Hinblick auf Konsortialverträge) . Die Datengrundlage des OAM fußt auf verschiedenen externen bibliometrischen Datendiensten (unter anderem Dimensions, Directory of Open Access Journals, Unpaywall), welche über eine Datenstelle aggregiert werden. Das OAM-Projekt wird vom Forschungszentrum Jülich geleitet. 

Im April 2021 veröffentlichte das Forschungszentrum Jülich einen vollständigen Auszug aller hybriden Zeitschriften, die im OAM enthalten sind. Das hierbei zur Verfügung gestellte [Datenset](https://data.fz-juelich.de/dataset.xhtml?persistentId=doi:10.26165/JUELICH-DATA/VTQXLM) besteht aus 22 CSV-Dateien. Jede Datei ist dabei einem Verlag bzw. einem Transformationsvertrag zugeordnet und enthält ausschließlich entsprechende Publikationsangaben. Eine Tabelle enthält im Regelfall den Zeitschriftentitel sowie die zugehörige p-ISSN (print ISSN) sowie e-ISSN (electronic ISSN). Eine ISSN ist eine internationale Standardnummer, die Zeitschriften und Schriftenreihen eindeutig identifiziert. 

Die Tabellen zeichnen sich durch kleinere Strukturunterschiede aus. So sind etwa Spaltennamen nicht einheitlich benannt. Die Handhabung von Mehrfachzuordnungen wird in den Tabellen unterschiedlich gelöst. Auch werden bei den Tabellen unterschiedliche Zeichenkodierungen (UTF-8 und Latin-1) verwendet. Dementsprechend ist mit der Aggregation aller Tabellen ein kleiner Aufwand verbunden, welchen ich mit dem beigefügten [Jupyter Notebook]() minimieren möchte. 

Zusätzlich habe ich in meinem Skript die aggregierte Tabelle mit ISSN-Ls (ISSN-Linking) angereichert. Die dafür genutzten Tabelle kann [hier]() heruntergeladen werden. 

Die aggregierte OAM-Tabelle mit allen hybriden Zeitschriften kann [hier]() heruntergeladen werden. Einzelne Zeilen wurden dabei von mir nachträglich verändert (im Bezug auf vereinzelt fehlende ISSN-Ls). Im Hinblick auf Reproduzierbarkeit kann aber auch das beiliegende [Jupyter Notebook]() zur Erstellung der unveränderten vollständigen Tabelle zurückgegriffen werden.
